# Contenu du fichier compose.dev.yml.
# Environnement de Developpement
# --------------------------------------------
# A LIRE AVANT DE COMMENCER
# --------------------------------------------
# Ce fichier contient les configurations spécifiques à l'environnement de développement.
# Chaque service importe les configurations de production du fichier docker-compose.yml et les configurations spécifiques à l'environnement de développement.
# Les paramètres déjà présents dans le fichier docker-compose.yml seront écrasés par ceux de ce fichier.
# --------------------------------------------
#
# --------------------------------------------
# EXEMPLE DE CONFIGURATION
# -------------------------------------------
services:
  mon_app_exemple:
    build:
      context: .
      dockerfile: docker/mon_app_exemple/build.Dockerfile
    ports:
      - "3333:3333"
  nginx:
    container_name: nginx_dev
    extends:
      service: nginx
      file: docker-compose.yml

  redis:
    container_name: redis-dev
    extends:
      service: redis
      file: docker-compose.yml
