# Contenu du fichier Dockerfile pour l'image des applications

# Build
# FROM ...

# --------------------------------------------

# Env. Production

# - Frontend
# FROM ...

# - Backend
# FROM ...

# --------------------------------------------

# Env. Developpement 

# - Frontend
# FROM ...

# - Backend
# FROM ...
